FROM python:3.12
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DB_WAIT_TIMEOUT=60
ENV DB_WAIT_INTERVAL=2
ENV SKIP_MIGRATIONS=false
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
COPY docker-entrypoint.sh ./
RUN chmod +x ./docker-entrypoint.sh
EXPOSE 8000
# if script fails, container stops
ENTRYPOINT ["./docker-entrypoint.sh"] 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
